### ISSUE TITLE
Fleet screen app crash when opening it with 12 (30) fleets in the air

### ISSUE THREAD

**Issue by vksavochkin** [ddialer/GE#12]
1.
Reporter1: >30 incoming rips, game crashes when sliding right menu. Works well when only 15 incoming (iPhone 4s, iPad 2)
Reporter2: 12 incoming waves, game crashes.
Reporter3: sending multiple transports, game crashes (iPhone 4s).

2.
When it not crashes on multiple fleets it needs scroll up, and not responsible (?)

**Comment by lilmnm-kamikaze-** [comment]
1.
Repo1: Are these only on iphone? or for both android and IOS?  are they Destroy missions or just normal attack missions? If they are destroy missions are they going to the same moon or are they going to different moons? and same question but for the normal attack missions.
Repo2: and Repo3: i have no idea really could be data being sent to much where it causes a timeout or memory leak on the device its self which will cause a crash.

2.
could be a refresh issue where the page doesnt reload and gets its updated data from the server?

**Comment by ddialer** [comment]
There can be two possible issues. First is widget that used to display sidebar navigation menu (jquery.mmenu) and may use a lot of resources when generate side page. Second is timers code, I'm not sure about this one. May be worse to remove sidebar navigation from fleet activity screen and replace it with custom simple animation.

**Comment by vksavochkin** [comment]
We have a lot of timers on planetchooser screen (I've seen 12x2 timers
during the game, and nobody reported crashes here), so we have one
suspect --- mmenu. We definitely have to replace sidebar fleet info
screen with something else, cause even if it not crashes --- it
renders improperly when fleet list is larger than screen height.

**Comment by ddialer** [comment]
that what i think. I may doo something like this http://www.jqueryscript.net/demo/Responsive-Sidebar-Push-Menu-with-jQuery-CSS3/# its just css sidebar and I can replace it both side bars this way and get rid of mmenu plugin

**Comment by ddialer** [comment]
I successfully replace mmenu with css. but there is are but. I can't test it on old android devices (v2) but pretty sure it should work. Also in old fleet screen I  used slide effect to display full fleet info, in this version I made it the same as phalanx (accordion effect). please check it and let me know if you want to keep accordion or make old style sliding effect. Also I uploaded all updated code to ge.seazonegames.com

**Comment by lilmnm-kamikaze-** [comment]
i can test on an old android device running android 2.3

**Comment by ddialer** [comment]
please when you have chance

**Comment by lilmnm-kamikaze-** [comment]
seems to be working. But swift swipping back and forth still causes a glitch where the left menu is partially displayed on the Fleet screen

**Comment by ddialer** [comment]
just submitted fix for swipe gesture. can you try again. on iphone everything looks fine for me

**Comment by lilmnm-kamikaze-** [comment]
ill try it right now

**Comment by vksavochkin** [comment]
On my android 4.4 and 4.2 seems to be working. This accordion allows to open multiple fleets simultaneously - it is awesome!

Only note is left menu not hides when tapping any entry, like it should.
Second note: main page should be locked from unintentional tapping like it did, otherwise it is hard to close menu without making random actions.

**Comment by vksavochkin** [comment]
Third note: list of fleets doesn't updates when tapping "recall" like it did before.

**Comment by vksavochkin** [comment]
Fourth note: opening accordion should scroll list so it fit screen. At least for last item in fleets list.

**Comment by vksavochkin** [comment]
There is swipe gesture? It never worked for me, neither in app nor in browser.

**Comment by lilmnm-kamikaze-** [comment]
it worked on the latest Firefox browser. I havn't tested the browser version on my phone just the app version

**Comment by ddialer** [comment]
Yes there is touch gestures used to open sidebars)
I updated touch library to newer version, so it should support more browsers

So for now is fixed:
click on left sidebar will open new page and close sidebar;
recall button now update fleet list;
main page is locked now when sidebar is open;

**Comment by vksavochkin** [comment]
Swipe now working on Nexus, confirmed.
